### ISSUE TITLE
Add options to `init` to populate metadata.yml.

### ISSUE THREAD

**Issue by Dimrok** [docker/app#100]
Currently

`docker-app init scratch` gives:

`metadata.yml`:
```
version: 0.1.0
name: scratch
description: ""
maintainers:
- name: root
  email: ""
targets:
  swarm: true
  kubernetes: true
```

# Proposition: Add an option for every single entry.  

`docker-app init scratch --description "An app built from scratch" --maintainer "antony:antony.mechin@docker.com" --maintainer "dimrok:dimrok@gmail.com"` gives:

`metadata.yml`:
```
version: 0.1.0
name: scratch
description: "An app built from scratch"
maintainers:
- name: antony
  email: antony.mechin@docker.com
- name: dimrok
  email: dimrok@gmail.com
targets:
  swarm: true
  kubernetes: true
```
