### ISSUE TITLE
Network options get expanded incorrectly

### ISSUE THREAD

**Issue by garethr** [docker/app#113]
Using the following Compsoe file 

```yaml
version: '3.5'
services:
  hello:
    image: hashicorp/http-echo:${version}
    command: ["-text", "${text}"]
    ports:
     - ${port}:5678
    networks:
     - backend
```

When this is rendered note the expansion of the list to include `null`.

```yaml
version: "3.5"
services:
  hello:
    command:
    - -text
    - hello world
    image: hashicorp/http-echo:latest
    networks:
      backend: null
    ports:
    - mode: ingress
      target: 5678
      published: 8080
      protocol: tcp
```
