### ISSUE TITLE
Disabling a node in YAML should be explicit

### ISSUE THREAD

**Issue by silvin-lubecki** [docker/app#261]
**Description**

A YAML node can be disabled using a "enabled" key with a value:
```yaml
version: "3.4"
services:
  monitor:
    enabled: "! ${myapp.debug}"
```
But the [code handling this feature](https://github.com/docker/app/blob/master/internal/templateloader/loader.go#L53) says that no value means disabling the node too:
```yaml
version: "3.4"
services:
  monitor:
    enabled: # monitor is disabled
```
I suggest we should remove this implicit disable with no value, and error out, as I think that enabling should be explicit too.
