### ISSUE TITLE
Recursive variable interpolation

### ISSUE THREAD

**Issue by nobecutan** [docker/app#288]
**Description**
It would be great if variables of settings.yml, or an external config, could be used again in the same file, as in:

```
version: 0.1.0
name: test
description:
maintainers:
  - name: admin
    email: admin@test.com
targets:
  swarm: true
  kubernetes: true

--
version: "3.6"
services:
  service1:
    image: some_service:1.0.0
    environment:
      DATASOURCE_URL: ${service1.db.url}
  service2:
    image: other_service:1.0.0
    environment:
      DATASOURCE_URL: ${service2.db.url}

--
service1:
  db:
    url: URL_TO_DB

service2:
  db:
    url: ${service1.db.url}
```

Now an external configuration could set only `service1.db.url` to change the DB connection of both services or set both values to use different DBs.

**Describe the results you received:**
```
version: "3.6"
services:
  service1:
    environment:
      DATASOURCE_URL: URL_TO_DB
    image: some_service:1.0.0
  service2:
    environment:
      DATASOURCE_URL: ${service1.db.url}
    image: other_service:1.0.0
```

**Describe the results you expected:**
```
version: "3.6"
services:
  service1:
    environment:
      DATASOURCE_URL: URL_TO_DB
    image: some_service:1.0.0
  service2:
    environment:
      DATASOURCE_URL: URL_TO_DB
    image: other_service:1.0.0
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker-app version`:**

```
Version:      v0.3.0
Git commit:   fba6a09
Built:        Fri Jun 29 13:09:30 2018
OS/Arch:      linux/amd64
Experimental: off
Renderers:    none
```
