### ISSUE TITLE
Allow variables to expand to hashes, or, how to override stuff for local development.

### ISSUE THREAD

**Issue by Fuco1** [docker/app#307]
Say I have a docker-compose with a `networks` section.  In production I attach to some external network that provides some shared services

```yaml
networks:
  service-tier:
    external:
      name: shared_services
```

Locally however, I run these as separate services from a `docker-compose.local.yml` and I access them through the local `back-tier` network.  Because locally the `shared_services` network does not exist I need to override it with `{}` to make compose happy.

So I hoped I could do something like

```yaml
networks:
  service-tier: ${service-tier}
---
service-tier:
  external:
    name: be_shared_services
```

and then render the local version with `--set service-tier={}` or some such.

However, `docker-app` complains with

```
> docker-app render                                                                                                                                              (1) :matus/use-dobi-for-builds
Error: failed to load Compose file: networks.service-tier must be a mapping or null
```

Am I doing something conceptually wrong? Is this not how docker-app is supposed to be used?  I would think it annoying to maintain multiple ways to start applications and if I could simply keep a `local.yml` which would then be added to `docker-app -f local.yml` that would be much nicer than rendering the prod version and attaching local compose files.  But maybe I'm wrong in my thinking /shrug.
