### ISSUE TITLE
FR: Render orchestrator specific templating.

### ISSUE THREAD

**Issue by ChristianKniep** [docker/app#316]
**Description**
In order to resume operations for a given tasks in case the tasks is rescheduled, I like to use `{{.Tasks.Slot}}`. 
Here `KAFKA_BROKER_ID={{.Task.Slot}}` and `hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"`.

Otherwise each kafka-broker would pick up a new broker-ID, which does not make sense.
The hostname makes it easy to spot which broker-id is used by which tasks.

```
version: '3'
services:
  zookeeper:
    image: qnib/${zk_img_name}:${zk_img_tag}
  zkui:
    image: qnib/plain-zkui:${zkui_img_tag}
    ports:
      - "${zkui_port}:9090"
  broker:
    image: qnib/${kafka_img_name}:${kafka_img_tag}
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    deploy:
      replicas: 3
    environment:
      - KAFKA_BROKER_ID={{.Task.Slot}}
      - LOG_MESSAGE_FORMAT_VERSION=${kafka_log_msg_format}
  manager:
    image: qnib/plain-kafka-manager:${kmanager_img_tag}
    ports:
      - "${kmanager_port}:9000"
    environment:
      ZOOKEEPER_HOSTS: "tasks.zookeeper:2181"
```

Using the experimental templating flag, `{{.Task.Slot}}` is interpreted as configuration.

**Describe the results you received:**
When rendering, I get:

```
$ docker-app render
Error: failed to execute go template: template: compose:12:25: executing "compose" at <.Service.Name>: map has no entry for key "Service"
```
As the renderer fails when interpreting the hostname.

**Describe the results you expected:**

I would like to use those templates - maybe even agnostic to the orchestrator, so that I use a generic template that will be filled out depending on the orchestrator.
Alternatively a condition can be made, which let's me drop it in case I do not use SWARM.

**Output of `docker version`:**

```
Client:
 Version:      18.06.0-ce-rc3
 API version:  1.38
 Go version:   go1.10.3
 Git commit:   cbfa3d9
 Built:        Thu Jul 12 05:15:46 2018
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Engine:
  Version:      18.06.0-ce-rc3
  API version:  1.38 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   cbfa3d9
  Built:        Thu Jul 12 05:26:13 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Output of `docker-app version`:**

```
docker-app version
Version:      v0.3.0-83-gc05143e
Git commit:   c05143e
Built:        Thu Jul 26 05:06:45 2018
OS/Arch:      darwin/amd64
Experimental: on
Renderers:    gotemplate, mustache, none, yatee
```

**Output of `docker info`:**

```
Containers: 45
 Running: 19
 Paused: 0
 Stopped: 26
Images: 142
Server Version: 18.06.0-ce-rc3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: ntmgx18xgesozgsy2dsgzb4b9
 Is Manager: true
 ClusterID: yolyvxvy2bjceh662p8bt17av
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 9.744GiB
Name: linuxkit-025000000001
ID: BXDU:L4YL:7GPX:DOI3:JWXD:DSUG:SXVD:DKVL:EAO7:VKNO:HNO6:DQWL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 150
 Goroutines: 269
 System Time: 2018-07-26T07:55:13.8281597Z
 EventsListeners: 3
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 ec2-34-242-200-232.eu-west-1.compute.amazonaws.com
 127.0.0.0/8
Live Restore Enabled: false
```
