### ISSUE TITLE
docker-app inspect command should print the missing settings and warn if any setting is unused in the compose file

### ISSUE THREAD

**Issue by silvin-lubecki** [docker/app#319]
`docker-app inspect` print the settings it founds in the `settings.yaml` file, but some settings may be missing and should be added manually while rendering or deploying the app.

Some other settings can also be forgotten by the user during a refactoring and are now unused.

Something like this
```sh
$ cat settings-app.dockerapp
```
```yaml
# Version of the application
version: 0.1.0
# Name of the application
name: settings-app
---
version: '3.3'

services:
  myservice:
    image: myprefix/my-image:${myservice.missing.tag}
    ports:
     - "${myservice.used.port}:80"
---
# Settings.
myservice:
  used:
    port: 8080
  unused:
    port: 8081
```

Inspect should print something like this:
```sh
$ docker-app inspect settings-app.dockerapp
settings-app 0.1.0

Setting                 Default
-------                 -------
myservice.used.port     8080

Missing Setting
---------------
myservice.missing.tag

Unused Setting            Default
--------------            -------
myservice.unused.port     8081
```
