### ISSUE TITLE
FR: Create POD with multiple containers

### ISSUE THREAD

**Issue by ChristianKniep** [docker/app#341]
**Description**
I got a use-case in which a simulation container is controlled by a policy container and the policy container is exchanging models with a trainer. The simulation and policy containers are tightly coupled and are scaled out to allow multiple simulations to feed the trainer.

```
        trainer - policy1 - simulation1
      /       \
  policy2      policy3 - simulation3
     |
simulation2
```
The trainer is started as a single compose file, creating the network `trainer-net`.

Using docker-compose the bundle of policy and simulation controller are deployed using this file:
```
version: '3.6'
services:
  sim:
    image: qnib/simulation
    networks:
      - sim-net
  policy:
    image: qnib/policy
    networks:
      - sim-net
      - trainer-net
networks:
  trainer-net:
    attachable: true
```
To scale I run it multiple time:
`$ for i in {1..12};do docker stack deploy -c docker-compose.yml sim${i};done`

**Overarching Goal**
I am going to provide a kubernetes deployment using pods in this case. What I would like to do is to provide a docker-compose file that is rending pods for kube, so that the user does not need to care which orchestrator to use. It will work in both deployments - even though the kube one uses pods and thus, is more scalable and (likely) performant.

**Describe the results you received:**
This works, but it screams to use pods for the bundle of simulation and policy container.

**Describe the results you expected:**
Not sure how to design this, but might it be possible to introduce the concept of pods to `docker-app`, so that deploying to SWARM uses distinct services and kubernetes creates pods?

To reduce the complexity, only accounting for network connectivity in pods, by creating a network that is shared between all containers within the pod?
Ideally by placing the services on the same host and reuse the network namespace - but that generates a scheduling problem.
