### ISSUE TITLE
[Enhancement Request] - Use version metadata in docker-app configuration as an environment variable

### ISSUE THREAD

**Issue by jhrabi** [docker/app#399]
I have a case where I want to keep a version of an image used in the docker app configuration to have the same tag as the version of the docker-app configuration. It would be useful if we could reference the version of the docker-app configuration as an environment variable in the settings part of the file.

Example:
```
# This section contains your application metadata.
# Version of the application
version: 1.1.0
...
---
# This section contains the Compose file that describes your application services.
...
---
# This section contains the default values for your application settings.
CONTAINER_TAG: ${DOCKERAPP_VERSION}
```

**Comment by mnottale** [comment]
Hi. Though not exactly what you ask, the metadata are exposed as variables using the `app.` prefix.
So in your compose file you can do
```
services:
  myserver:
    image: myserver:${app.version}
```

**Comment by jhrabi** [comment]
It's really close to what I'm looking for, but it looks like the settings doesn't intepret the app.version value. Using the following example:

```
version: nanoserver
name: helloworld
---
version: "3.6"
services:
  helloworld:
    image: helloworld:${CONTAINER_TAG}

---
CONTAINER_TAG: ${app.version}
```

I get the following from docker-app render:

```
version: "3.6"
services:
  helloworld:
    image: helloworld:${app.version}
```

As oppose to what I would expect which is
```
version: "3.6"
services:
  helloworld:
    image: helloworld:nanoserver
```

I'm looking for this specific behaviour so I can override the app.version value assigned to the tag if required.
