### ISSUE TITLE
.env files unpacked and also referenced (redundant)

### ISSUE THREAD

**Issue by BillMills** [docker/app#495]
**Description**

`docker app render` produces a compose file with environment variables explicitly hard-coded and referenced from an external file, which is redundant & confusing.

**Steps to reproduce the issue:**

1. Make a compose file:

```
version: "3.7"

services:
  db:
    image: postgres:9.6
    env_file:
      - myvars.env
    configs:
      - source: initscript
        target: /docker-entrypoint-initdb.d/init.sh
    secrets:
      - password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/password

configs:
  initscript:
    file: ./db-init.sh

secrets:
  password:
    external: true
```

2. Make a file `myvars.env`:

```
POSTGRES_USER=moby
POSTGRES_DB=mydb
```

3. init and render the result:

```
docker app init demo
docker app render demo

version: "3.7"
services:
  db:
    configs:
    - source: initscript
      target: /docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD_FILE: /run/secrets/password
      POSTGRES_USER: moby
    env_file:
    - myvars.env
    image: postgres:9.6
    secrets:
    - source: password
secrets:
  password:
    name: password
    external: true
configs:
  initscript:
    file: db-init.sh

```

All the variables from `myvars.env` have been populated explicitly in the `environment` key, but there's also still an `env_file` key; there should be one or the other. My preference would be 'don't mess up my compose file by unpacking my env file', but that's a matter of opinion.

**Output of `docker version`:**

```
Client:
 Version:           0.0.0-20190308210551-485aab6
 API version:       1.40
 Go version:        go1.11.5
 Git commit:        485aab6
 Built:             Fri Mar  8 21:16:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          0.0.0-20190308210551-485aab6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.5
  Git commit:       485aab6
  Built:            Fri Mar  8 21:11:20 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.4
  GitCommit:        e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        6635b4f0c6af3810594d2770f662f34ddc15b40d
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-app version`:**

```
-bash: docker-app: command not found
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application Packages (Docker Inc., v0.6.0-126-g207a9459e7)
  assemble: assemble is a high-level build tool (Docker Inc., v0.29.0-11-gd83e9c4)
  pipeline:  (Docker Inc., v0.3.2)
  registry: Manage Docker registries (Docker Inc., 0.1.0)

Server:
 Containers: 46
  Running: 41
  Paused: 0
  Stopped: 5
 Images: 38
 Server Version: 0.0.0-20190308210551-485aab6
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 2fjey4jdrje9vczv7hhy7j60p
  Is Manager: true
  ClusterID: zwh29ubi3jei6al6601hqun4i
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
   External CAs:
     cfssl: https://172.31.22.167:12381/api/v1/cfssl/sign
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 172.31.22.167
  Manager Addresses:
   172.31.22.167:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
 runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-862.14.4.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.637GiB
 Name: ip-172-31-22-167.ec2.internal
 ID: LRA2:IVHP:L22E:3AEB:ZSWD:N6XP:7AXV:OGLP:U42T:SCSS:JPWW:T5H6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: billmills
 Registry: https://index.docker.io/v1/
 Labels:
  com.docker.security.seccomp=enabled
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Quantity: 10 Nodes	Expiration date: 2019-03-28	License is currently active
```
