### ISSUE TITLE
Render randomness between dot notation and pure yaml variables

### ISSUE THREAD

**Issue by Sirtea** [docker/app#549]
**Description**

When declaring vars in .dockerapp file and replacing with a yaml file:
* If dockerapp uses dot notation, yaml file must use dot notation
* If dockerapp uses yaml tabular spec, yaml file must the same tabular spec
* Any other combination leads to randomness between renders

**Steps to reproduce the issue:**

1. Create a dockerapp file using dot notation

```
gerard@atlantis:~/workspace/example$ cat example.dockerapp 
version: 0.1.0
name: example
description: 
maintainers:
  - name: sirtea
    email: 

---
version: "3.6"
services:
  any:
    image: none/none
    environment:
      SSH_USER: ${ssh.user}

---

ssh.user: FILLME
gerard@atlantis:~/workspace/example$ 
```

2. Create a yaml file not using dot notation

```
gerard@atlantis:~/workspace/example$ cat params.yml 
ssh:
  user: sirtea
gerard@atlantis:~/workspace/example$ 
```

3. Render the compose file (easier to see than deploying) a few times and compare results:

```
gerard@atlantis:~/workspace/example$ docker-app render example.dockerapp -f params.yml 
version: "3.6"
services:
  any:
    environment:
      SSH_USER: sirtea
    image: none/none
gerard@atlantis:~/workspace/example$ docker-app render example.dockerapp -f params.yml 
version: "3.6"
services:
  any:
    environment:
      SSH_USER: FILLME
    image: none/none
gerard@atlantis:~/workspace/example$ 
```

4. This also happens with yaml tabular spec in dockerapp, and dot notation on yaml file, but it does not happen if the two use the same yaml style

**Describe the results you received:**

Sometimes I get the variables replaced, and sometimes not. Completely at random, but close to 50-50%

**Describe the results you expected:**

Repeatability at minimum

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
gerard@atlantis:~/workspace/example$ docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
gerard@atlantis:~/workspace/example$ 
```

**Output of `docker-app version`:**

```
gerard@atlantis:~/workspace/example$ docker-app version
Version:      v0.6.0
Git commit:   9f9c6680
Built:        Thu Oct  4 13:30:33 2018
OS/Arch:      linux/amd64
Experimental: off
Renderers:    none
gerard@atlantis:~/workspace/example$ 
```

**Output of `docker info`:**

```
gerard@atlantis:~/workspace/example$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: nk1jtjnjcp04wzyj3f71lr2en
 Is Manager: true
 ClusterID: xf1kvn3f58e40rx8migm7teci
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.8.169
 Manager Addresses:
  192.168.8.169:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-9-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.57GiB
Name: atlantis
ID: TTBA:5DAK:VRH2:XGWT:UK5A:I6SV:XDM6:GRTG:GSGL:IBLH:JHQP:XGHW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: <set but secret>
HTTPS Proxy: <set but secret>
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
gerard@atlantis:~/workspace/example$ 
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Irrelevant, but a physical desktop end user machine.
The swarm is empty, but the bug happens before messing with docker. It's a templating problem.
