### ISSUE TITLE
Substitute parameters before validation

### ISSUE THREAD

**Issue by eliaskoromilas** [docker/app#811]
**Description**

`docker app build/validate` does not involve parameter substitution -> _false negatives_

**Steps to reproduce the issue:**
1. *docker-compose.yml*
```yml
version: '3.2'
services:
  hello-world:
    image: hello-world
    volumes:
    - ${test}:/path/to/bar
```
2. *parameters.yml*
```yml
test: /path/to/foo
```
3. `docker app build .` / `docker app validate`

**Describe the results you received:**

```
Compose file validation failed:
* can't use relative path as volume source ("${test}:/path/to/bar") in service "hello-world"
```

**Describe the results you expected:**

```
Validated "hello-world.dockerapp"
```

**Output of `docker version`:**

```
Docker version 20.10.5, build 55c4c88
```

**Output of `docker app version`:**

```
Version:               v0.9.1-beta3
Git commit:            9d2c67f8
OS/Arch:               linux/amd64
```
